services:
  postgis:
    image: postgis/postgis:15-3.4
    restart: always
    env_file:
      - ./env/db.env
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./docker/init-user-db.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - "${POSTGRES_PORT}:5432"

  backend:
    build: .
    env_file:
      - ./env/backend.env
    volumes:
      - .:/app:rw
    ports:
      - "8000:8000"
    depends_on:
      - postgis

volumes:
  db:
