services:
  postgis:
    image: postgis/postgis:15-3.4
    restart: always
    env_file:
      - ./env/db.env
    volumes:
      - ./db:/var/lib/postgresql/data:z
      - ./docker/init-user-db.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - 5435:5432
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'",
        ]
      interval: 10s
      timeout: 3s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./env/backend.env
    volumes:
      - .:/app:rw
    ports:
      - 8000:8000
    depends_on:
      postgis:
        condition: service_healthy

volumes:
  db:
