services:
  postgis:
    build:
      context: ./postgis
    restart: always
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5435:5432

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    command: gunicorn cosia_back.wsgi:application --bind 0.0.0.0:8000
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_HOST=${PGHOST}
      - POSTGRES_PORT=${PGPORT}
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - postgis

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - web

volumes:
  db:
  static_volume:
