services:
  postgis:
    build:
      context: ./postgis
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data:z
    ports:
      - 5436:5432
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      command: python3 manage.py test
    volumes:
      - ..:/app:rw
    ports:
      - 8000:8000
    depends_on:
      - postgis

volumes:
  db:
