services:
  postgis:
    build:
      context: ./postgis
    restart: always
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5436:5432

  admin:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    command: gunicorn cosia_back.wsgi:application --bind 0.0.0.0:8000
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_HOST=${PGHOST}
      - POSTGRES_PORT=${PGPORT}
    ports:
      - 8000:8000
    depends_on:
      - postgis

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    command: gunicorn cosia_back.wsgi:application
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_HOST=${PGHOST}
      - POSTGRES_PORT=${PGPORT}
    depends_on:
      - postgis

volumes:
  db:
