services:
  postgis:
    build:
      context: ./postgis
    restart: always
    env_file:
      - ./env/db.env
    volumes:
      - ./db:/var/lib/postgresql/data:z
    ports:
      - 5435:5432

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ./env/backend.env
    volumes:
      - ..:/app:rw
    ports:
      - 8000:8000
    depends_on:
      - postgis

volumes:
  db:
