name: Black and test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  black:
    name: Black check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgis:
        image: postgis/postgis:15-3.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install libs
        run: |
          apt-get install -y -qq wget build-essential gdal-bin binutils libproj-dev libgdal-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install braintree mysqlclient apprise

      - name: Run Tests
        run: python manage.py test
