name: Black and test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  black:
    name: Black check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker/compose.dev.yml"
        env:
          PGPASSWORD: "postgres"
          PGDATABASE: "cosia_db"

      - name: Run tests
        run: docker compose -f docker/compose.dev.yml exec web python3 manage.py test
