name: Black and test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  black:
    name: Black check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgis:
        image: postgis/postgis:15-3.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install libs
        run: |
          apt-get update -qq && apt-get install -y -qq \
          # std libs
          git less nano curl \
          ca-certificates \
          wget build-essential\
          # python basic libs
          python3.11 python3.11-dev python3.11-venv gettext \
          # geodjango
          gdal-bin binutils libproj-dev libgdal-dev \
          # postgresql
          libpq-dev postgresql-client && \
          apt-get clean all && rm -rf /var/apt/lists/* && rm -rf /var/cache/apt/*

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install braintree mysqlclient apprise

      - name: Run Tests
        run: python manage.py test
