name: Black

on:
  pull_request:
    branches: ["master"]

jobs:
  black:
    name: Black check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Black
        uses: RojerGS/python-black-check@master
        with:
          line-length: "88"
