name: Publish latest on Docker Hub

on:
  push:
    branches:
      - master

jobs:
  black:
    name: Black check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:15-3.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: cosia_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install libs
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq wget build-essential gdal-bin binutils libproj-dev libgdal-dev postgresql-client

      - name: Install dependencies
        run: |
          python -m pip install -U setuptools
          pip install -r requirements.txt

      - name: Run Tests
        run: python manage.py test
        env:
          POSTGRES_HOST: "localhost"

  publish_latest_on_dockerhub:
    name: Publish on dockerhub as latest
    runs-on: ubuntu-latest

    needs:
      - black
      - test

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: maximallain/cosia_back:latest
          file: docker/Dockerfile.prod
