name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  black:
    name: Black check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:15-3.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: cosia_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install libs
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq wget build-essential gdal-bin binutils libproj-dev libgdal-dev postgresql-client

      - name: Install dependencies
        run: |
          python -m pip install -U setuptools
          pip install -r requirements.txt

      - name: Run Tests
        run: python manage.py test
        env:
          POSTGRES_HOST: "localhost"

  get_tag:
    name: Get tag
    runs-on: ubuntu-latest
    needs:
      - black
      - test

    outputs:
      new_version: ${{ steps.get_version.outputs.SOURCE_TAG }}

    steps:
      - name: Branch name
        id: get_version
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

  # Unabled because of IGN network... When l'usine logicielle is open on internet => let's go !
  # trigger_deployment_pipeline:
  #   name: Trigger deployment pipeline
  #   runs-on: ubuntu-latest
  #   needs:
  #     - publish_latest_on_dockerhub
  #   steps:
  #     - name: Fetch gitlab webhook
  #       uses: joelwmale/webhook-action@master
  #       with:
  #         url: https://gitlab.gpf-tech.ign.fr/api/v4/projects/701/ref/master/trigger/pipeline?token=${{ secrets.DEV_TRIGGER_GITLAB_TOKEN }}

  publish_version_on_dockerhub:
    name: Publish new tag on dockerhub
    runs-on: ubuntu-latest

    needs:
      - get_tag

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: maximallain/cosia_back:${{needs.get_tag.outputs.new_version}}
          file: docker/Dockerfile.prod
